/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Complaint = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'userName' : IDL.Text,
  'title' : IDL.Text,
  'area' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'assignedWorkerId' : IDL.Opt(IDL.Principal),
  'updatedAt' : IDL.Int,
  'category' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'assignedWorkerName' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Category = IDL.Variant({
  'other' : IDL.Null,
  'drainage' : IDL.Null,
  'garbage' : IDL.Null,
  'electricity' : IDL.Null,
  'road_damage' : IDL.Null,
  'water_leakage' : IDL.Null,
});
export const Stats = IDL.Record({
  'total' : IDL.Nat,
  'pending' : IDL.Nat,
  'completed' : IDL.Nat,
  'underProcess' : IDL.Nat,
});
export const Worker = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
});
export const ComplaintRequest = IDL.Record({
  'title' : IDL.Text,
  'area' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'photo' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addWorker' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignComplaint' : IDL.Func([IDL.Nat, IDL.Principal, IDL.Text], [], []),
  'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getAssignedComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplaintById' : IDL.Func([IDL.Nat], [IDL.Opt(Complaint)], ['query']),
  'getComplaintsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getMyComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeWorker' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitComplaint' : IDL.Func([ComplaintRequest], [IDL.Nat], []),
  'updateComplaintStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Complaint = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'userName' : IDL.Text,
    'title' : IDL.Text,
    'area' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'assignedWorkerId' : IDL.Opt(IDL.Principal),
    'updatedAt' : IDL.Int,
    'category' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'assignedWorkerName' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Category = IDL.Variant({
    'other' : IDL.Null,
    'drainage' : IDL.Null,
    'garbage' : IDL.Null,
    'electricity' : IDL.Null,
    'road_damage' : IDL.Null,
    'water_leakage' : IDL.Null,
  });
  const Stats = IDL.Record({
    'total' : IDL.Nat,
    'pending' : IDL.Nat,
    'completed' : IDL.Nat,
    'underProcess' : IDL.Nat,
  });
  const Worker = IDL.Record({ 'principal' : IDL.Principal, 'name' : IDL.Text });
  const ComplaintRequest = IDL.Record({
    'title' : IDL.Text,
    'area' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'photo' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addWorker' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignComplaint' : IDL.Func([IDL.Nat, IDL.Principal, IDL.Text], [], []),
    'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getAssignedComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplaintById' : IDL.Func([IDL.Nat], [IDL.Opt(Complaint)], ['query']),
    'getComplaintsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getMyComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeWorker' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitComplaint' : IDL.Func([ComplaintRequest], [IDL.Nat], []),
    'updateComplaintStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };