/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'other' : null } |
  { 'drainage' : null } |
  { 'garbage' : null } |
  { 'electricity' : null } |
  { 'road_damage' : null } |
  { 'water_leakage' : null };
export interface Complaint {
  'id' : bigint,
  'status' : string,
  'userName' : string,
  'title' : string,
  'area' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'assignedWorkerId' : [] | [Principal],
  'updatedAt' : bigint,
  'category' : string,
  'photo' : [] | [ExternalBlob],
  'assignedWorkerName' : [] | [string],
}
export interface ComplaintRequest {
  'title' : string,
  'area' : string,
  'description' : string,
  'category' : Category,
  'photo' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface Stats {
  'total' : bigint,
  'pending' : bigint,
  'completed' : bigint,
  'underProcess' : bigint,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Worker { 'principal' : Principal, 'name' : string }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addWorker' : ActorMethod<[Principal, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignComplaint' : ActorMethod<[bigint, Principal, string], undefined>,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getAssignedComplaints' : ActorMethod<[], Array<Complaint>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaintById' : ActorMethod<[bigint], [] | [Complaint]>,
  'getComplaintsByCategory' : ActorMethod<[Category], Array<Complaint>>,
  'getMyComplaints' : ActorMethod<[], Array<Complaint>>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkers' : ActorMethod<[], Array<Worker>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeWorker' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selfRegister' : ActorMethod<[], undefined>,
  'submitComplaint' : ActorMethod<[ComplaintRequest], bigint>,
  'updateComplaintStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
